// components/dashboard/employee/data.ts

import { Conversation } from "./types";

export const myConversations: Conversation[] = [
  {
    id: 1,
    customerName: "احمد نوری",
    customerPhone: "09121234567",
    customerInitial: "ا",
    subject: "مشکل پرداخت",
    lastMessage: "ممنون از پاسختون. چک کردم ولی هنوز مشکل حل نشده...",
    time: "۲ دقیقه پیش",
    status: "waiting",
    department: "پشتیبانی",
    assignee: "علی احمدی",
    source: "ویجت سایت",
    startDate: "امروز ساعت ۱۴:۳۰",
    lastActivity: "۲ دقیقه پیش",
    unreadCount: 2,
    isUrgent: true,
    messages: [
      { id: 1, senderName: "احمد نوری", text: "سلام. من چند روز پیش یک سفارش ثبت کردم ولی هنوز پرداختم تایید نشده. میشه بررسی کنید؟", time: "۱۴:۳۱", isSupport: false },
      { id: 2, senderName: "علی احمدی", text: "سلام جناب نوری. بله حتماً بررسی می‌کنم. کد پیگیری سفارشتون رو دارید؟", time: "۱۴:۳۲", isSupport: true },
      { id: 3, senderName: "احمد نوری", text: "بله. کد پیگیری ۱۲۳۴۵۶۷۸۹۰ هست", time: "۱۴:۳۳", isSupport: false },
      { id: 4, senderName: "علی احمدی", text: "بررسی کردم. مشکل از سمت درگاه پرداخت بوده. باید با واحد مالی هماهنگ کنم.", time: "۱۴:۳۵", isSupport: true, isInternalNote: true },
      { id: 5, senderName: "علی احمدی", text: "ممنون از صبرتون. بررسی کردم، پرداخت شما موفق بوده ولی به دلیل تاخیر در سیستم بانکی هنوز تایید نشده. تا ۲۴ ساعت آینده تایید میشه و سفارشتون ارسال خواهد شد.", time: "۱۴:۳۸", isSupport: true },
      { id: 6, senderName: "احمد نوری", text: "ممنون از پاسختون. چک کردم ولی هنوز مشکل حل نشده. میشه دوباره بررسی کنید؟", time: "۱۵:۱۲", isSupport: false },
      { id: 7, senderName: "احمد نوری", text: "الان ساعت ۳ بعد از ظهره و هنوز تغییری نکرده", time: "۱۵:۱۳", isSupport: false },
    ],
  },
  {
    id: 2,
    customerName: "فاطمه حسینی",
    customerPhone: "09127654321",
    customerInitial: "ف",
    subject: "پیگیری سفارش",
    lastMessage: "بله متوجه شدم. پس فردا برام ارسال میشه؟",
    time: "۱۵ دقیقه پیش",
    status: "answered",
    department: "پشتیبانی",
    assignee: "علی احمدی",
    source: "ویجت سایت",
    startDate: "امروز ساعت ۱۳:۰۰",
    lastActivity: "۱۵ دقیقه پیش",
    messages: [],
  },
  {
    id: 3,
    customerName: "محمد رضایی",
    customerPhone: "09129876543",
    customerInitial: "م",
    subject: "سوال قبل از خرید",
    lastMessage: "سلام. میخواستم در مورد تور کیش اطلاعات بگیرم",
    time: "۳۰ دقیقه پیش",
    status: "open",
    department: "فروش",
    assignee: "علی احمدی",
    source: "ویجت سایت",
    startDate: "امروز ساعت ۱۲:۰۰",
    lastActivity: "۳۰ دقیقه پیش",
    unreadCount: 1,
    messages: [],
  },
  {
    id: 4,
    customerName: "سارا کریمی",
    customerPhone: "09123456789",
    customerInitial: "س",
    subject: "پیگیری سفارش",
    lastMessage: "ممنون از راهنماییتون",
    time: "۱ ساعت پیش",
    status: "answered",
    department: "پشتیبانی",
    assignee: "علی احمدی",
    source: "ویجت سایت",
    startDate: "امروز ساعت ۱۱:۰۰",
    lastActivity: "۱ ساعت پیش",
    messages: [],
  },
];

export const statusConfig = {
  waiting: { label: "در انتظار", color: "bg-[rgba(242,184,75,0.1)] text-[#f2b84b]", dotColor: "bg-[#f2b84b]" },
  answered: { label: "پاسخ داده شده", color: "bg-[rgba(89,216,195,0.1)] text-[#59D8C3]", dotColor: "bg-[#59D8C3]" },
  open: { label: "باز", color: "bg-[rgba(77,171,247,0.1)] text-[#4dabf7]", dotColor: "bg-[#4dabf7]" },
  closed: { label: "بسته شده", color: "bg-[rgba(111,136,128,0.1)] text-gray-400", dotColor: "bg-gray-500" },
};