// components/dashboard/members/data.ts
import { Member, Department } from "./types";

export const departments: Department[] = [
  { id: 1, name: "پشتیبانی" },
  { id: 2, name: "فروش" },
  { id: 3, name: "مالی" },
  { id: 4, name: "پیگیری سفارش" },
  { id: 5, name: "سایر موارد" },
];

export const membersData: Member[] = [
  {
    id: 1,
    firstName: "سارا",
    lastName: "احمدی",
    username: "sara.ahmadi",
    phone: "09121234567",
    role: "مدیر دپارتمان",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "active",
    presence: "online",
    lastActivity: "۲ دقیقه پیش",
    openTickets: 5,
  },
  {
    id: 2,
    firstName: "امیر",
    lastName: "حسینی",
    username: "amir.hosseini",
    phone: "09129876543",
    role: "مدیر دپارتمان",
    departmentId: 2,
    departmentName: "فروش",
    status: "active",
    presence: "online",
    lastActivity: "۵ دقیقه پیش",
    openTickets: 3,
  },
  {
    id: 3,
    firstName: "مهدی",
    lastName: "رضایی",
    username: "mehdi.rezaei",
    phone: "09135551234",
    role: "مدیر دپارتمان",
    departmentId: 3,
    departmentName: "مالی",
    status: "active",
    presence: "offline",
    lastActivity: "۳۰ دقیقه پیش",
    openTickets: 1,
  },
  {
    id: 4,
    firstName: "نیلوفر",
    lastName: "محمدی",
    username: "niloofar.mohammadi",
    phone: "09123335566",
    role: "کارمند",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "active",
    presence: "online",
    lastActivity: "۱ دقیقه پیش",
    openTickets: 4,
  },
  {
    id: 5,
    firstName: "رضا",
    lastName: "کریمی",
    username: "reza.karimi",
    phone: "09127778899",
    role: "کارمند",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "active",
    presence: "online",
    lastActivity: "۱۵ دقیقه پیش",
    openTickets: 2,
  },
  {
    id: 6,
    firstName: "زهرا",
    lastName: "نوری",
    username: "zahra.noori",
    phone: "09131112233",
    role: "کارمند",
    departmentId: 2,
    departmentName: "فروش",
    status: "active",
    presence: "offline",
    lastActivity: "۱ ساعت پیش",
    openTickets: 1,
  },
  {
    id: 7,
    firstName: "علی",
    lastName: "صالحی",
    username: "ali.salehi",
    phone: "09124445566",
    role: "کارمند",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "active",
    presence: "offline",
    lastActivity: "۲ ساعت پیش",
    openTickets: 0,
  },
  {
    id: 8,
    firstName: "مریم",
    lastName: "فتحی",
    username: "maryam.fathi",
    phone: "09137776655",
    role: "کارمند",
    departmentId: 3,
    departmentName: "مالی",
    status: "active",
    presence: "online",
    lastActivity: "۱۰ دقیقه پیش",
    openTickets: 1,
  },
  {
    id: 9,
    firstName: "حسین",
    lastName: "ناصری",
    username: "hosein.naseri",
    phone: "09121119988",
    role: "کارمند",
    departmentId: 2,
    departmentName: "فروش",
    status: "active",
    presence: "offline",
    lastActivity: "۳ ساعت پیش",
    openTickets: 0,
  },
  {
    id: 10,
    firstName: "فاطمه",
    lastName: "اکبری",
    username: "fatemeh.akbari",
    phone: "09135558877",
    role: "کارمند",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "inactive",
    presence: "offline",
    lastActivity: "۱ هفته پیش",
    openTickets: 0,
  },
  {
    id: 11,
    firstName: "پویا",
    lastName: "رحیمی",
    username: "pouya.rahimi",
    phone: "09126663322",
    role: "کارمند",
    departmentId: 1,
    departmentName: "پشتیبانی",
    status: "active",
    presence: "offline",
    lastActivity: "۴ ساعت پیش",
    openTickets: 0,
  },
  {
    id: 12,
    firstName: "شیدا",
    lastName: "حسنی",
    username: "sheyda.hasani",
    phone: "09139994455",
    role: "کارمند",
    departmentId: 2,
    departmentName: "فروش",
    status: "active",
    presence: "online",
    lastActivity: "۸ دقیقه پیش",
    openTickets: 2,
  },
];

export const statsData = {
  totalMembers: 12,
  managersCount: 3,
  activeStaffCount: 8,
  inactiveMembersCount: 1,
};