// components/dashboard/departments/data.ts
import { Department } from "./types";

export const departmentsData: Department[] = [
  {
    id: 1,
    name: "پشتیبانی",
    manager: "سارا احمدی",
    description: "پاسخگویی به سوالات فنی و مشکلات مشتریان",
    status: "active",
    memberCount: 8,
    openTickets: 12,
    avgResponseTime: "۵ دقیقه",
    color: "#59D8C3",
    statusType: "normal",
  },
  {
    id: 2,
    name: "فروش",
    manager: "امیر حسینی",
    description: "مشاوره و فروش محصولات و خدمات",
    status: "active",
    memberCount: 5,
    openTickets: 8,
    avgResponseTime: "۸ دقیقه",
    color: "#F2B84B",
    statusType: "busy",
  },
  {
    id: 3,
    name: "مالی",
    manager: "مهدی رضایی",
    description: "پیگیری پرداخت‌ها، صورت‌حساب‌ها و موارد مالی",
    status: "active",
    memberCount: 3,
    openTickets: 2,
    avgResponseTime: "۱۵ دقیقه",
    color: "#8B7FDF",
    statusType: "normal",
  },
  {
    id: 4,
    name: "پیگیری سفارش",
    manager: "",
    description: "وضعیت سفارشات، تحویل و ارسال",
    status: "active",
    memberCount: 2,
    openTickets: 1,
    avgResponseTime: "۳۵ دقیقه",
    color: "#FF6B6B",
    statusType: "attention",
  },
  {
    id: 5,
    name: "سایر موارد",
    manager: "",
    description: "سوالات عمومی و موارد غیر مرتبط با بخش‌های اصلی",
    status: "inactive",
    memberCount: 0,
    openTickets: 0,
    avgResponseTime: "-",
    color: "#9CA3AF",
    statusType: "normal",
  },
];

export const statsData = {
  totalDepartments: 5,
  activeDepartments: 4,
  totalOpenTickets: 23,
  attentionNeeded: 1,
};